kind: PersistentVolume
apiVersion: v1
metadata:
  name: ml-mysql-initdb-storage
  namespace: fika
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vukasin/fika/domaci/model_training/scripts"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ml-mysql-initdb-claim
  namespace: fika
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
