# python_file:
#   class: File
#   path: app/network.py
# dataset:
#   class: File
#   path: app/banknote_dataset.csv
# k: 2
# num_of_epochs: 2
# k_array: [0, 1]
python_file2:
  class: File
  path: collect_results.py
array_of_outputs: ["fasd", "fasd", "fasd", "fasd"]